server:
  port : 8081

database:
  timeout: 20

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hack_app
    username: root
    password: Password1

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect